# Page settings
baseurl = "localhost:1313"
title = "GopherCon Singapore 2018"
languageCode = "en-us"
theme = ""

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = ""
  # Navigation
  [params.navigation]
    brand    = "GopherCon Singapore 2018"
    home     = "Home"
    workshop = "Workshop"
    schedule = "Schedule"
    speakers = "Speakers"
    venue    = "Venue"
    team     = "Team"
    conduct  = "Conduct"
    ticket   = "Ticket"
    pastvideo= "2017 Videos"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "Do something you love."
    

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.workshop]
    enable = true
    map = true
    form = true
    title = "Go Workshop"
    date = "May 03, 2018"
    venue = "TBC"
    profile = "bill.jpg"
    instructor="William Kennedy"
    instructorbio="William Kennedy is a managing partner at Ardan Studio in Miami, Florida, a mobile, web, and systems development company. He is also a co-author of the book Go in Action, the author of the blog GoingGo.Net, and a founding member of GoBridge which is working to increase Go adoption through diversity."
    fundamentalsdescription = "This class provides an idiomatic introduction to the Go programming language supported by extensive examples and hands-on exercises. We focus on both the specification and implementation of the language including topics ranging from language syntax, Goâ€™s type system, testing and more. We believe this class is perfect for anyone who wants a jump start in learning Go."
    ultimatedescription="This is for any intermediate-level developer who has some experience with other programming languages and wants to learn Go. This class will provide a jump start in learning Go and provide a more thorough understanding of the language and its internals."
    mapiframeurl = "https://www.google.com/maps/embed/v1/place?q=singapore&key=AIzaSyAV_g95uyyqNxmyTKx1IkdPXtKCnDAElc0"

    [[params.workshop.outline.fundamentals]]
      item="Philosophy of Go"
    [[params.workshop.outline.fundamentals]]
      item="Language Syntax"
    [[params.workshop.outline.fundamentals]]
      item="Using Pointers"
    [[params.workshop.outline.fundamentals]]
      item="Arrays, Slices and Maps"
    [[params.workshop.outline.fundamentals]]
      item="Methods and Interfaces"
    [[params.workshop.outline.fundamentals]]
      item="Packaging and Exporting"
    [[params.workshop.outline.fundamentals]]
      item="Testing"
    [[params.workshop.outline.fundamentals]]
      item="Managing External Dependencies"
    [[params.workshop.outline.fundamentals]]
      item="Standard Library"

    [[params.workshop.outline.ultimate]]
      item="Language Syntax"
    [[params.workshop.outline.ultimate]]
      item="Data Structures"
    [[params.workshop.outline.ultimate]]
      item="Decoupling"
    [[params.workshop.outline.ultimate]]
      item="Concurrency"

  # Work section
  [params.schedule]
    enable = false
    title = "Schedule"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'

  # speakers section
  [params.speakers]
    enable = true 
    title = "Speakers"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
      person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"
    
  # venue section
  [params.venue]
    enable = false
    title = "Venue"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.services.item]]
      title = "Brand &amp; Strategy"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-anchor"

    [[params.services.item]]
      title = "Web &amp; Interface"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-layers2"
    [[params.services.item]]
      title = "Photo &amp; Video"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-video2"

      [[params.services.item]]
      title = "CMS &amp; eCommerce"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"      
      icon = "icon-monitor"

  # Team section
  [params.team]
    enable = false
    title = "Team"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.team.item]]
      name = "Jean Smith"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person1.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.team.item]]
      name = "Rob Smith"
      position = "Web Developer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person2.jpg"
      alt = "Person2"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-github", "#"]
      ]

    [[params.team.item]]
      name = "Larry Ben"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person3.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#"]
      ]
 

  # Contact section
  [params.conduct]
    enable = true
    map = true
    form = true
    title = "Code of Conduct"
    paragraph01 = "All attendees, speakers, sponsors and volunteers at our conference are required to agree with the following code of conduct. Organisers will enforce this code throughout the event. We expect cooperation from all participants to help ensure a safe environment for everybody."
    paragraph02 = "Our conference is dedicated to providing a harassment-free conference experience for everyone, regardless of gender, gender identity and expression, age, sexual orientation, disability, physical appearance, body size, race, ethnicity, religion (or lack thereof), or technology choices. We do not tolerate harassment of conference participants in any form. Sexual language and imagery is not appropriate for any conference venue, including talks, workshops, parties, Twitter and other online media. Conference participants violating these rules may be sanctioned or expelled from the conference without a refund at the discretion of the conference organisers."
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "5555 Love Paradise 56 New Clity 5655, <br> Excel Tower United Kingdom"],
        ["icon-phone", "(123) 465-6789"],
        ["icon-envelope", "info@freehtml5.co"],
        ["icon-globe", '<a href="http://freehtml5.co/" target="_blank">freehtml5.co</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Ticket section
  [params.ticket]
    enable = false 
    title = "Tickets"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'

  # 2017 Video
  [params.pastvideo]
    enable = false 
    title = "Work"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'

    [[params.pastvideo.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "Project 1"
      subtitle = "Branding"

    [[params.pastvideo.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Project 2"
      subtitle = "Design"

    [[params.pastvideo.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "Project 3"
      subtitle = "Design"

    [[params.pastvideo.row]]
      img = "work_4.jpg"
      alt = "Image4"
      title = "Project 4"
      subtitle = "Design"

    [[params.pastvideo.row]]
      img = "work_5.jpg"
      alt = "Image5"
      title = "Project 5"
      subtitle = "Design"

    [[params.pastvideo.row]]
      img = "work_6.jpg"
      alt = "Image6"
      title = "Project 6"
      subtitle = "Design"

  # Footer section
  [params.footer]
    enable = true
    description = "hello@gophercon.sg"
